# This is a basic workflow to help you get started with Actions

name: ASG Continuous Deployment


on:
  workflow_run:
    workflows: ["RDS Continuous Deployment"]
    types:
      - completed

# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Validate code
        working-directory: ASG
        run: |
          terraform init
          terraform validate


      # Runs a set of commands using the runners shell
      - name: Workspace
        working-directory: ASG
        run: |
          terraform workspace select dev || terraform workspace new dev
         


      #################################################################################################################################################
      ##################################################  VIRGINIA REGION  ############################################################################
      #################################################################################################################################################


      # - name: Plan
      #   working-directory: ASG
      #   run: |
      #     terraform plan -var-file envs/virginia.tfvars



      # - name:   Apply
      #   working-directory: ASG
      #   run: |
      #     terraform apply	-var-file envs/virginia.tfvars --auto-approve




      ###################################################################################################################################################


      # - name: Plan
      #   working-directory: ASG
      #   run: |
      #     terraform plan -var-file envs/virginia.tfvars



      # - name:   Destroy
      #   working-directory: ASG
      #   run: |
      #     terraform destroy	-var-file envs/virginia.tfvars --auto-approve




     ##################################################################################################################################################
     ###################################################    OHIO REGION   #############################################################################
     ##################################################################################################################################################

      # - name: Plan
      #   working-directory: ASG
      #   run: |
      #     terraform plan -var-file envs/ohio.tfvars 




      # - name:   Apply
      #   working-directory: ASG
      #   run: |
      #     terraform apply	-var-file envs/ohio.tfvars --auto-approve




      ##################################################################################################################################################
      
      # - name: Plan
      #   working-directory: ASG
      #   run: |
      #     terraform plan -var-file envs/ohio.tfvars 


      # - name:   Destroy 
      #   working-directory: ASG
      #   run: |
      #     terraform destroy	-var-file envs/ohio.tfvars --auto-approve



      ################################################################################################################################################
      ###################################################    OREGON REGION   #########################################################################
      ################################################################################################################################################

      - name: Plan
        working-directory: ASG
        run: |
          terraform plan -var-file envs/oregon.tfvars 



      - name:   Apply 
        working-directory: ASG
        run: |
          terraform apply	-var-file envs/oregon.tfvars --auto-approve

      #################################################################################################################################################



      # - name: Plan
      #   working-directory: ASG
      #   run: |
      #     terraform plan -var-file envs/oregon.tfvars       


      # - name:   Destroy
      #   working-directory: ASG
      #   run: |
      #     terraform destroy	-var-file envs/oregon.tfvars --auto-approve 